name: scouting_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  circular_menu: ^4.0.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.4
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - gg.MP4

